%define name	perl-MP3-ID3v1Tag
%define version 1.11
%define release %mkrel 7

Summary:	MP3-ID3v1Tag module for perl 
Name:		%{name}
Version:	%{version}
Release:	%{release}
License:	GPL or Artistic
Group:		Development/Perl
Source0:	MP3-ID3v1Tag-1.11.tar.bz2
URL:		http://www.cpan.org
BuildRequires:	perl-devel
Buildarch:	noarch
BuildRoot:	%{_tmppath}/%{name}-%{version}-%{release}-buildroot

%description
MP3-ID3v1Tag module for perl

%prep
%setup -q -n MP3-ID3v1Tag-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make
make test

%install
rm -rf $RPM_BUILD_ROOT
%makeinstall_std

%clean 
rm -rf %{buildroot}

%files
%defattr(-,root,root)
%doc Changes README
%{perl_vendorlib}/MP3/*
%{_mandir}/*/*


* Fri Oct 15 2004 Oden Eriksson <oeriksson@mandrakesoft.com> 1.11-6mdk
- fix deps

* Thu Aug 14 2003 Per Øyvind Karlsen <peroyvind@linux-mandrake.com> 1.11-5mdk
- rebuild for new perl
- don't rm -rf $RPM_BUILD_ROOT in %%prep
- drop $RPM_OPT_FLAGS, noarch..
- use %%makeinstall_std macro

* Wed May 28 2003 Thierry Vignaud <tvignaud@mandrakesoft.com> 1.11-4mdk
- rebuild for new auto{prov,req}

* Thu Jan 16 2003 Oden Eriksson <oden.eriksson@kvikkjokk.net> 1.11-3mdk
- build release

* Wed Jul 31 2002 Lenny Cartier <lenny@mandrakesoft.com> 1.11-2mdk
- rebuild with new perl

* Fri Mar 01 2002 Lenny Cartier <lenny@mandrakesoft.com> 1.11-1mdk
- 1.11

* Sun Nov 4 2001 Oden Eriksson <oden.eriksson@linux-mandrake.com> 1.10-2mdk
- rewrote the spec file

* Sun Nov 4 2001 Oden Eriksson <oden.eriksson@linux-mandrake.com>
- Spec file was autogenerated. 
